name: Linux

on:
  pull_request:
    branches: [ main ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux arm64 gcc
            key: linux-gcc-arm64
            os: [ self-hosted, linux, ARM64 ]
            cmake_params: ''
            threads_count: 4

    name: CMake (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: ${{github.workspace}}/${{github.actor}}-${{ github.head_ref }}/${{ matrix.config.key }}
          key: ${{github.actor}}-${{ github.head_ref }}-${{ matrix.config.key }}

      - name: Create build dir
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{github.workspace}}/${{github.actor}}-${{ github.head_ref }}/${{ matrix.config.key }}

      - name: Build
        run: |
          cmake ${{ matrix.config.cmake_params }} -G Ninja \
            -B ${{github.workspace}}/${{github.actor}}-${{ github.head_ref }}/${{ matrix.config.key }} \
            -DCMAKE_BUILD_TYPE=Debug -DCCL_STRICT_COMPILATION=ON -DCCL_LIBCPP=OFF -DCCL_ADDRESS_SANITIZER=ON \
            -DCCL_PRECOMPILED_HEADERS=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
            -DCMAKE_TOOLCHAIN_FILE=/home/cerberus-project_2/vcpkg/scripts/buildsystems/vcpkg.cmake
          
          cmake --build ${{github.workspace}}/${{github.actor}}-${{ github.head_ref }}/${{ matrix.config.key }} -j ${{ matrix.config.threads_count }}

      - name: Test
        run: |
          cd ${{github.workspace}}/${{github.actor}}-${{ github.head_ref }}/${{ matrix.config.key }}
          ctest -j ${{ matrix.config.threads_count }}
          cd ..
